class V1::SessionsController < ApplicationController

  def create #login
    @user = User.find_by(email: params[:email])
    if @user && @user.valid_password?(params[:password])
      render json: @user
    else
      head(:unauthorized)
    end
  end

  def destroy #logout
    if current_user
      #a new user token will be autogenerated when set to nil
      current_user.authentication_token = nil
      if current_user.save
        head(:ok)
      else
        head(:internal_server_error)
      end
    else
      head(:unauthorized)
    end
  end

end
