class V1::SessionsController < ApplicationController

  def create #login
    @user = User.find_by(email: params[:email])
    if @user && @user.valid_password?(params[:password])
      render json: @user
    else
      # could also return head(:unauthorized), but easier to just check the status in React reducer
      render json: {status: 'not_authenticated'}
    end
  end

  def destroy #logout
    if current_user
      #a new token will be autogenerated when set to nil
      current_user.authentication_token = nil
      if current_user.save
        head(:ok)
      else
        render json: {status: 'error - check sessions#destroy'}
      end
    else
      render json: {status: 'not_authenticated'}
    end
  end

end
